services:
  - type: web
    name: pulse-server
    env: python
    buildCommand: >
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&
      apt-get install -y nodejs &&
      pip install flask &&
      pip install -U "yt-dlp[default]"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000